palette = "cores"

format = """ 
[█](fg:blue)\
$os\
[](bg:white fg:blue)\
$username\
$hostname\
[](bg:cinza_escuro fg:white)\
$directory\
[ ](fg:cinza_escuro)\
$git_branch\
$git_status\
$python\
($cmd_duration )\
$character"""

[line_break]
disabled = true

[palettes.cores]
cinza_escuro = "#444444"
cinza_fechado = "#9CA4B5"
cinza_medio = "#BAC3CF"

[username]
show_always = true
format = '[ $user](bg:white fg:black bold)'
disabled = false

[hostname]
disabled = false
format = '[@$hostname](bg:white fg:black bold)'

[os]
disabled = false
style = 'bg:blue fg:black'
[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[cmd_duration]
format = "[$duration](fg:red)"

[directory]
format = "[ $path](bg:cinza_escuro fg:cinza_fechado)"
truncation_length = 2
truncation_symbol = "…/"

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[\\$](bold white)"
disabled = false

[fossil_branch]
symbol = "  "
format = '[$symbol($version)]($style)'

[git_branch]
symbol = "󰊢 "
style = "fg:cinza_medio"
format = '[$symbol($branch) ($version)]($style)'

[git_commit]
tag_symbol = '  '
format = '[$symbol($version)]($style)'

[python]
format = '[(\($virtualenv\) )](fg:cinza_medio)'
