general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando principal que chama o seu hyprlock
    before_sleep_cmd = loginctl lock-session    # Garante que a tela seja bloqueada antes de suspender o PC
    after_sleep_cmd = hyprctl dispatch dpms on  # Garante que a tela ligue novamente ao acordar
}

# Desliga a tela em 30s APENAS SE o hyprlock estiver na tela
listener {
    timeout = 30
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = pidof hyprlock && hyprctl dispatch dpms on
}

# "Hyprlocka" automaticamente em 5 min
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# Desligar a tela do monitor ao "Hyprlockar" dps de 30s
listener {
    timeout = 330                                 
    on-timeout = hyprctl dispatch dpms off        # Comando que desliga o sinal de vídeo
    on-resume = hyprctl dispatch dpms on          # Liga a tela de volta quando você mexer o mouse
}
